config/routes.rb
Rails.application.routes.draw do
	
	root 'resumes#index'

	 get 'resumes/pdf/:id', to: 'resumes#pdf'
	resources :resumes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  
  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  def pdf
    # resumes = Resume.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ResumePdf.new()
        send_data pdf.render,
          filename: "resume",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.fetch(:resume, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeDesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resumes/_form.html.erb
<%= form_with(model: resume, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
        <% resume.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'PDF', "resumes/pdf/#{resume.id}.pdf"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>